version: "3.7"

services:
  web1:
    image: nginx:latest
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - "10000:80"
  web2:
    image: nginx:latest
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - "20000:80"
